package com.example.myapplication

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.Button
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.material3.TextField
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import coil.compose.AsyncImage

data class FilmModel(
    val id: String,
    val posterUrl: String,
    val name: String,
    val description: String?,
    val releaseDate: Int
)

object DataRepository {
    var filmsList by mutableStateOf<List<FilmModel>>(emptyList())
}

fun generateRandomFilms(count: Int): List<FilmModel> {
    val names = listOf(
        "Interstellar", "Inception", "Parasite", "Whiplash", "Amelie",
        "Gladiator", "Titanic", "Joker", "Coco", "Nomadland"
    )
    return (1..count).map { index ->
        val randomId = index.toString()
        FilmModel(
            id = randomId,
            posterUrl = "https://picsum.photos/seed/$randomId/300/450",
            name = names.random(),
            description = null,
            releaseDate = (1990..2023).random()
        )
    }
}

@Composable
fun FirstScreen(onNavigateToSecond: () -> Unit) {
    var inputText by remember { mutableStateOf("") }
    var isGenerated by remember { mutableStateOf(false) }

    val count = inputText.toIntOrNull()
    val isValidNumber = count != null && count > 0

    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(16.dp),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.Center
    ) {
        TextField(
            value = inputText,
            onValueChange = { newValue ->
                inputText = newValue
                isGenerated = false
            },
            label = { Text("Введите число") }
        )

        Button(
            onClick = {
                DataRepository.filmsList = generateRandomFilms(count!!)
                isGenerated = true
            },
            enabled = isValidNumber
        ) {
            Text("Сгенерировать")
        }

        Button(
            onClick = onNavigateToSecond,
            enabled = isGenerated
        ) {
            Text("Перейти к списку")
        }
    }
}

@Composable
fun SecondScreen() {
    var query by remember { mutableStateOf("") }
    var displayedList by remember { mutableStateOf(DataRepository.filmsList) }
    var message by remember { mutableStateOf("") }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(16.dp)
    ) {
        TextField(
            value = query,
            onValueChange = { newValue -> query = newValue },
            label = { Text("Введите год") },
            modifier = Modifier.fillMaxWidth()
        )

        Button(onClick = {
            if (query.isBlank()) {
                displayedList = DataRepository.filmsList
                message = ""
            } else {
                val year = query.toIntOrNull()
                if (year != null) {
                    val filtered = DataRepository.filmsList.filter { it.releaseDate <= year }
                    if (filtered.isEmpty()) {
                        displayedList = emptyList()
                        message = "Ничего не найдено"
                    } else {
                        displayedList = filtered
                        message = ""
                    }
                } else {
                    message = "Введите корректный год"
                }
            }
        }) {
            Text("Сортировать")
        }

        if (message.isNotEmpty()) {
            Text(message)
        } else {
            LazyColumn {
                items(displayedList) { film ->
                    FilmItem(film)
                }
            }
        }
    }
}

@Composable
fun FilmItem(film: FilmModel) {
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .padding(8.dp),
        verticalAlignment = Alignment.CenterVertically
    ) {
        AsyncImage(
            model = film.posterUrl,
            contentDescription = null,
            modifier = Modifier.size(80.dp)
        )
        Spacer(modifier = Modifier.width(16.dp))
        Text(text = film.name)
    }
}